name: .NET

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
    
    - name: First interaction
      uses: actions/first-interaction@v1.1.0
      with:
        # Token for the repository. Can be passed in using {{ secrets.GITHUB_TOKEN }}
        repo-token: secrets.GITHUB_TOKEN
        # Comment to post on an individual's first issue
        issue-message: "yippeee this is your first issue"
        # Comment to post on an individual's first pull request
        pr-message: "yippeee this is your first first pull request"
